"use client";
import {useState} from "react"; import type {StoredScreening} from "@/services/types";
const gradeNames=["No DR","Mild NPDR","Moderate NPDR","Severe NPDR","Proliferative DR"];
export function ReportDownload({result,reportNumber}:{result:StoredScreening;reportNumber:string}){const[working,setWorking]=useState(false);async function download(){setWorking(true);try{const{jsPDF}=await import("jspdf");const{default:html2canvas}=await import("html2canvas");const summary=document.getElementById("executive-summary");const summaryImage=summary?(await html2canvas(summary,{scale:2,backgroundColor:"#FFFFFF",useCORS:true})).toDataURL("image/png"):null;const doc=new jsPDF({unit:"mm",format:"a4"});const date=new Date(result.timestamp).toLocaleString();const probabilities=result.probabilities??{};
  // Page 1 — cover
  doc.setFillColor(250,250,247);doc.rect(0,0,210,297,"F");doc.setTextColor(27,77,110);doc.setFont("times","bold");doc.setFontSize(27);doc.text("OcuScreen",105,83,{align:"center"});doc.setDrawColor(184,150,62);doc.line(85,91,125,91);doc.setTextColor(26,26,26);doc.setFontSize(21);doc.text("Retinal Screening Report",105,109,{align:"center"});doc.setFont("helvetica","normal");doc.setFontSize(9);doc.setTextColor(107,114,128);doc.text(reportNumber,105,123,{align:"center"});doc.text(date,105,130,{align:"center"});doc.text(`Model v${result.model_version}`,105,137,{align:"center"});doc.setFillColor(240,247,250);doc.roundedRect(55,171,100,15,3,3,"F");doc.setTextColor(27,77,110);doc.setFont("helvetica","bold");doc.text("CONFIDENTIAL — FOR CLINICAL USE ONLY",105,181,{align:"center"});
  // Page 2 — summary and imaging
  doc.addPage();header(doc,"Clinical Summary",reportNumber);if(summaryImage)doc.addImage(summaryImage,"PNG",16,38,178,48,undefined,"FAST");doc.addImage(result.image_data_url,16,96,84,66,undefined,"FAST");doc.addImage(result.heatmap_base64,110,96,84,66,undefined,"FAST");doc.setFont("helvetica","normal");doc.setFontSize(7);doc.setTextColor(107,114,128);doc.text("ORIGINAL RETINAL CAPTURE",16,168);doc.text("AI ATTENTION MAP",110,168);
  // Page 3 — detailed analysis
  doc.addPage();header(doc,"Detailed Analysis",reportNumber);doc.setFont("helvetica","bold");doc.setFontSize(11);doc.setTextColor(26,26,26);doc.text("AI-DETECTED FINDINGS",16,37);doc.setFont("helvetica","normal");doc.setFontSize(9);let y=47;(result.hotspots??[]).forEach((spot,index)=>{doc.setTextColor(27,77,110);doc.text(`${index+1}. ${spot.description}`,16,y);doc.setTextColor(107,114,128);doc.text(`${spot.anatomy} | Activation ${Math.round(spot.activation*100)}%`,24,y+6);y+=17});doc.setFont("helvetica","bold");doc.setTextColor(26,26,26);doc.text("PROBABILITY DISTRIBUTION",16,y+7);doc.setFont("helvetica","normal");y+=17;gradeNames.forEach((label,grade)=>{const key=String(grade) as keyof typeof probabilities;const value=Number(probabilities[key]??0);doc.setTextColor(107,114,128);doc.text(`Grade ${grade} · ${label}`,16,y);doc.setTextColor(26,26,26);doc.text(`${(value*100).toFixed(1)}%`,95,y,{align:"right"});doc.setFillColor(232,228,223);doc.rect(105,y-3,80,3,"F");doc.setFillColor(grade<2?58:grade===2?212:196,grade<2?143:grade===2?145:69,grade<2?110:grade===2?59:77);doc.rect(105,y-3,80*value,3,"F");y+=10});doc.setFont("helvetica","bold");doc.text("HEALTHY-RETINA COMPARISON NOTES",16,y+10);doc.setFont("helvetica","normal");doc.setTextColor(107,114,128);doc.text(comparisonNotes[result.grade],16,y+18,{maxWidth:178});
  // Page 4 — education and notice
  doc.addPage();header(doc,"Understanding Your Result",reportNumber);doc.setFont("times","bold");doc.setFontSize(15);doc.setTextColor(26,26,26);doc.text("What is diabetic retinopathy?",16,40);doc.setFont("helvetica","normal");doc.setFontSize(9);doc.setTextColor(107,114,128);doc.text("Diabetic retinopathy is damage to the tiny blood vessels in the back of the eye caused by diabetes. Finding changes early can help prevent vision loss.",16,49,{maxWidth:178});doc.setFont("times","bold");doc.setFontSize(15);doc.setTextColor(26,26,26);doc.text("What should happen next?",16,75);doc.setFont("helvetica","normal");doc.setFontSize(9);doc.setTextColor(107,114,128);doc.text(nextSteps[result.grade],16,84,{maxWidth:178});doc.setFillColor(240,238,235);doc.roundedRect(16,223,178,43,3,3,"F");doc.setFont("helvetica","bold");doc.setTextColor(27,77,110);doc.text("IMPORTANT NOTICE",22,235);doc.setFont("helvetica","italic");doc.setTextColor(107,114,128);doc.text("OcuScreen is a decision-support and triage aid. It is not an FDA-cleared diagnostic device and does not replace examination by a licensed clinician. This report must be reviewed by a qualified healthcare professional.",22,244,{maxWidth:166});doc.save(`OcuScreen-${reportNumber}.pdf`)}finally{setWorking(false)}}return <button onClick={download} disabled={working} className="ghost-button">{working?"Preparing report…":"Download Report"}</button>}
function header(doc:import("jspdf").jsPDF,title:string,report:string){doc.setTextColor(27,77,110);doc.setFont("times","bold");doc.setFontSize(15);doc.text("OcuScreen",16,18);doc.setFont("helvetica","normal");doc.setFontSize(8);doc.setTextColor(156,163,175);doc.text(report,194,18,{align:"right"});doc.setDrawColor(232,228,223);doc.line(16,24,194,24);doc.setFont("times","bold");doc.setFontSize(19);doc.setTextColor(26,26,26);doc.text(title,16,32)}
const comparisonNotes=["No significant differences from a healthy reference were detected.","Subtle early changes may be present compared with a healthy retina.","Hemorrhages or hard exudates may be visible compared with a clear healthy retina.","Significant vascular changes may be present compared with normal smooth vasculature.","Extensive abnormal vessel growth or bleeding may be present and requires urgent review."];
const nextSteps=["Continue regular diabetes care and schedule another retinal screening in about 12 months.","Continue diabetes care and arrange routine clinical follow-up.","Schedule an ophthalmology appointment within 1–2 months and bring this report.","See an ophthalmologist as soon as possible, ideally within 2–4 weeks.","Seek urgent specialist care and contact a retinal specialist this week."];
