import {ClinicalImageAnalysis} from "./ClinicalImageAnalysis";import {Disclaimer} from "./Disclaimer";import {EducationAccordion} from "./EducationAccordion";import {ExecutiveSummary} from "./ExecutiveSummary";import {HealthyComparison} from "./HealthyComparison";import {ProbabilityChart} from "./ProbabilityChart";import {ReportDownload} from "./ReportDownload";import {RetinalIntelligence} from "./RetinalIntelligence";import {ScrollReveal} from "./ScrollReveal";import {SeverityScale} from "./SeverityScale";import type {StoredScreening} from "@/services/types";
export function ResultView({result}:{result:StoredScreening}){const reportNumber=makeReportNumber(result.timestamp);const probabilities=result.probabilities??{"0":result.grade===0?result.confidence:0,"1":result.grade===1?result.confidence:0,"2":result.grade===2?result.confidence:0,"3":result.grade===3?result.confidence:0,"4":result.grade===4?result.confidence:0};return <article id="screening-report"><header className="mb-9 flex flex-wrap items-end justify-between gap-7"><div><p className="report-label">Screening report</p><span className="mt-2 block h-0.5 w-14 bg-gold"/><h1 className="serif-title mt-5 text-4xl sm:text-5xl">Retinal Screening Report</h1><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 font-mono text-[11px] text-quiet"><span>{reportNumber}</span><span>{new Date(result.timestamp).toLocaleString()}</span><span>Model v{result.model_version}</span></div></div><ReportDownload result={{...result,probabilities}} reportNumber={reportNumber}/></header><ExecutiveSummary result={result}/>
  <ScrollReveal className="mt-20"><SectionHeader label="Retinal image analysis" title="Where the screening model focused" description="Review the original scan, the attention map, and plain-language explanations of the strongest model responses."/><ClinicalImageAnalysis result={result}/></ScrollReveal>
  <ScrollReveal className="mt-24"><SectionHeader label="Diagnostic confidence analysis" title="Understanding the model’s decision" description="The bars show every grade the model considered, while the scale places the selected grade in clinical context."/><div className="grid gap-7 lg:grid-cols-2"><ProbabilityChart probabilities={probabilities} predicted={result.grade}/><SeverityScale grade={result.grade}/></div></ScrollReveal>
  <ScrollReveal className="mt-24"><SectionHeader label="Retinal health intelligence" title="Clinical context at a glance" description="Trace the screening pathway, review where model attention is concentrated, and place the result in the context of the APTOS reference dataset."/><RetinalIntelligence result={result}/></ScrollReveal>
  <ScrollReveal className="mt-24"><HealthyComparison result={result}/></ScrollReveal>
  <ScrollReveal className="mt-24"><SectionHeader label="Understanding your results" title="Clear answers for the next conversation" description="Open each topic for a plain-language explanation that can be reviewed with a healthcare professional."/><EducationAccordion grade={result.grade}/></ScrollReveal>
  <ScrollReveal className="mt-20"><Disclaimer/></ScrollReveal>
  </article>}
function SectionHeader({label,title,description}:{label:string;title:string;description:string}){return <div className="mb-9 max-w-3xl"><p className="report-label">{label}</p><h2 className="serif-title mt-3 text-3xl sm:text-4xl">{title}</h2><p className="mt-4 text-sm leading-7 text-body">{description}</p></div>}
function makeReportNumber(timestamp:string){const date=new Date(timestamp);const year=date.getFullYear();const code=String(Math.abs(date.getTime())%10000).padStart(4,"0");return `#OCS-${year}-${code}`}
