"use client";
import {useRef,useState} from "react";
const MAX=10*1024*1024;
export function UploadZone({file,preview,disabled,onSelect}:{file:File|null;preview:string|null;disabled:boolean;onSelect:(file:File|null,error?:string)=>void}){const input=useRef<HTMLInputElement>(null);const[drag,setDrag]=useState(false);function validate(next?:File){if(!next)return;if(!["image/jpeg","image/png"].includes(next.type))return onSelect(null,"Please choose a JPEG or PNG image.");if(next.size>MAX)return onSelect(null,"The image must be 10 MB or smaller.");onSelect(next)}return <div>
  <button type="button" disabled={disabled} onClick={()=>input.current?.click()} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);validate(e.dataTransfer.files[0])}} className={`flex min-h-[285px] w-full flex-col items-center justify-center rounded-2xl border-2 border-dashed px-8 transition duration-200 ${drag?"border-sea bg-wash shadow-[0_0_0_5px_rgba(46,139,131,.08)]":"border-teal/35 bg-[#FCFDFC] hover:border-teal hover:bg-wash/50"}`}>
    <input ref={input} type="file" className="hidden" accept="image/jpeg,image/png" onChange={e=>validate(e.target.files?.[0])}/>
    <svg viewBox="0 0 80 52" className="h-16 w-24 text-teal" fill="none" aria-hidden="true"><path d="M4 26c8-14 20-21 36-21s28 7 36 21c-8 14-20 21-36 21S12 40 4 26Z" stroke="currentColor" strokeWidth="1.6"/><circle cx="40" cy="26" r="13" stroke="currentColor" strokeWidth="1.6"/><circle cx="40" cy="26" r="5" fill="currentColor" opacity=".22"/><path d="M40 12v28M26 26h28" stroke="currentColor" strokeWidth=".8" opacity=".35"/></svg>
    <span className="mt-6 text-base font-semibold text-ink">Drop image here or click to browse</span><span className="mt-2 text-sm text-body">Accepts JPEG and PNG · Maximum 10 MB</span>
  </button>
  {file&&preview&&<div className="page-in mt-6 overflow-hidden rounded-2xl border border-taupe bg-white p-3 shadow-clinical"><div className="relative aspect-video overflow-hidden rounded-xl bg-notice">{/* eslint-disable-next-line @next/next/no-img-element */}<img src={preview} alt="Selected retinal image" className="h-full w-full object-contain"/><button disabled={disabled} onClick={e=>{e.stopPropagation();onSelect(null)}} className="absolute right-3 top-3 min-h-12 rounded-full border border-taupe bg-white/95 px-4 text-xs font-semibold text-teal shadow-sm">Remove</button></div><div className="flex items-center justify-between gap-4 px-3 py-4 text-xs"><span className="truncate font-medium text-ink">{file.name}</span><span className="font-mono text-body">{(file.size/1048576).toFixed(2)} MB</span></div></div>}
  </div>}
